development:
  adapter: postgresql
  encoding: utf-8
  database: justin-and-abi_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf-8
  database: justin-and-abi_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: utf-8
  database: justin-and-abi_production
  pool: 5
